### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'reduce')

### ISSUE THREAD

**Issue by realyps** [hyoo-ru/draw.hyoo.ru#2]
Ошибка появляется если долго и быстро рисовать круги.
vector.ts:89 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'reduce')
    at $mol_vector.distance (vector.ts:8
    at $hyoo_draw.Root(0).Pane().Touch().event_move (touch.view.ts:150:56)
    at Object.pointermove (touch.view.tree.ts:360:40)
    at [object Object].pointermove(#).fresh (fiber.ts:167:42)
    at [object Object].pointermove(#).async (fiber.ts:254:10)
    at SVGSVGElement.$mol_wire_async (async.ts:21:19)

<img width="1468" alt="Screenshot 2022-12-05 at 09 33 05" src="https://user-images.githubusercontent.com/1780924/205608916-75ce2c5f-41b1-452c-bfe5-add6bcfbd434.png">
9:31)

**Comment by nin-jin** [comment]
Воспроизводится, когда курсор выходит за границы окна и возвращается обратно.

**Comment by nin-jin** [comment]
Починил, проверьте.

**Comment by realyps** [comment]
все супер! все работает!
